export const STUDENT = 'student:manage'
export const TEACHER = 'teacher:manage'
export const ROLE = 'role:manage'
export const PERMISSION = 'permission:manage'
export const COURSE = 'course:manage'
export const TEACHING_TASK = 'teaching-task:manage'
export const LOG = 'log:manage'
export const MONITOR = 'monitor:manage'
export const TASK_SCHEDULING = 'task-scheduling:manage'
export const FILE = 'file:manage'
export const DOCUMENT = 'document:manage'

